### ISSUE TITLE
Having trouble using the example app

### ISSUE THREAD

**Issue by ecoulson** [microsoft/VerifiableCredential-SDK-iOS#114]
Hello,

I was hoping to get a bit more guidance on how to use this SDK. I am a bit new to Swift development and am still learning the tools. I cloned the repository and opened it in XCode. I am getting errors in the submodules directory with PromiseKit and secp256k1. When building the project I am getting an error message from XCode stating that `secp256k1/bitcoin-core/secp256k1/include/secp256k1.h: No such file or directory`. Hoping to get some guidance on how to set up this SDK :).

**Comment by DannWu** [comment]
@ecoulson Did you find a solution to this?
